### ISSUE TITLE
Getting webpack error

### ISSUE THREAD

**Issue by winkler1** [limscoder/react-present#1]
$ webpack
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#style() is deprecated. Use Node#raw()
Node#before is deprecated. Use Node#raws.before
Node#_value was deprecated. Use Node#raws.value
Hash: 81b567f0ffd6e59f88ff
Version: webpack 1.12.2
Time: 3693ms
            Asset       Size  Chunks             Chunk Names
          wtf.gif     1.3 MB          [emitted]  
      dragons.gif     557 kB          [emitted]  
    lintProps.png      29 kB          [emitted]  
   react-conf.png    74.2 kB          [emitted]  
squirrel-fail.gif    2.02 MB          [emitted]  
   validation.png    30.7 kB          [emitted]  
         kitt.gif     608 kB          [emitted]  
       index.html  201 bytes          [emitted]  
         index.js    1.58 MB       0  [emitted]  index
      ./index.css    1.69 kB       0  [emitted]  index
     index.js.map    1.84 MB       0  [emitted]  index
  ./index.css.map   88 bytes       0  [emitted]  index
    + 298 hidden modules

ERROR in ./~/react-router/~/history/lib/useQueries.js
Module not found: Error: Cannot resolve module 'qs' in /Users/Jeff/repos/ghtemp/node_modules/react-router/node_modules/history/lib
 @ ./~/react-router/~/history/lib/useQueries.js 11:10-23

ERROR in ./~/react-router/~/history/lib/createHistory.js
Module not found: Error: Cannot resolve module 'deep-equal' in /Users/Jeff/repos/ghtemp/node_modules/react-router/node_modules/history/lib
 @ ./~/react-router/~/history/lib/createHistory.js 13:17-38
Child extract-text-webpack-plugin:
        + 2 hidden modules

**Comment by limscoder** [comment]
Here's my config: node 0.10.38, npm 2.14.7, webpack 1.12.2

I'd try that. I'm using those old versions just because that's what I need for some other projects. I'd hope everything works with newer versions, but it may not.

**Comment by limscoder** [comment]
Closing unless there's more information available for debugging.
